In [2]:
import numpy as np

In [3]:
p1 = np.full((4, 5), True)
p1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
a=np.arange(10,50)

print(list(a))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [6]:
b=list(map(lambda x:-1 if x%2==0 else x,a))
b

[-1,
 11,
 -1,
 13,
 -1,
 15,
 -1,
 17,
 -1,
 19,
 -1,
 21,
 -1,
 23,
 -1,
 25,
 -1,
 27,
 -1,
 29,
 -1,
 31,
 -1,
 33,
 -1,
 35,
 -1,
 37,
 -1,
 39,
 -1,
 41,
 -1,
 43,
 -1,
 45,
 -1,
 47,
 -1,
 49]

In [9]:
x = np.arange(1,20,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
j=list(map(lambda x:0 if x%3==0 else x,x))
j=np.array(j)
print(j)

[ 1  0  5  7  0 11 13  0 17 19]


In [18]:
j2=np.reshape(j,(2,5))
print(j2)

[[ 1  0  5  7  0]
 [11 13  0 17 19]]


In [24]:
j2[0,2]=0
j2[1,2]=0
j2

array([[ 1,  0,  0,  7,  0],
       [11, 13,  0, 17, 19]])

In [3]:
b1 = np.linspace(1.5, 3,9)
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [4]:
np.random.seed(1234)
b2= np.random.randint(0, 10, (3, 3))
b2

array([[3, 6, 5],
       [4, 8, 9],
       [1, 7, 9]])

In [28]:
np.linalg.det(b2)

-34.99999999999999

In [29]:
b2.transpose()

array([[3, 4, 1],
       [6, 8, 7],
       [5, 9, 9]])

In [45]:
b2.reshape(3,3)


array([[3, 6, 5],
       [4, 8, 9],
       [1, 7, 9]])

In [46]:
b1.reshape(3,3)



array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [51]:
np.sum(b1)


20.25

In [52]:
np.sum(b2)

52

In [53]:
np.sum(b2)+np.sum(b1)

72.25

In [8]:
b1.reshape(3,3)
b2

array([[3, 6, 5],
       [4, 8, 9],
       [1, 7, 9]])

In [12]:
b1=b1.reshape(3,3)
b1

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [14]:
b1+b2

array([[ 4.5   ,  7.6875,  6.875 ],
       [ 6.0625, 10.25  , 11.4375],
       [ 3.625 ,  9.8125, 12.    ]])

In [13]:
b1*b2

array([[ 4.5   , 10.125 ,  9.375 ],
       [ 8.25  , 18.    , 21.9375],
       [ 2.625 , 19.6875, 27.    ]])

In [15]:
np.mean(b2)

5.777777777777778

In [17]:
b2[b2>np.mean(b2)]


array([6, 8, 9, 7, 9])

In [18]:
from sklearn.preprocessing import minmax_scale

In [21]:
b2_scaled = np.apply_along_axis(minmax_scale, 1, b2)
b2_scaled

array([[0.        , 1.        , 0.66666667],
       [0.        , 0.8       , 1.        ],
       [0.        , 0.75      , 1.        ]])